{% set name = "napari-J" %}
{% set version = "0.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-J-{{ version }}.tar.gz
  sha256: 725ea90076b1ede3b7c70b9bb9b5d8a00e82bbe99508d23db5e246ca217308d0
  patches:
    - exclude_ijpb.patch

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools-scm
  run:
    - jpype1 >=1.2.1
    - matplotlib-base
    - napari
    - napari-plugin-engine >=0.1.4
    - numpy
    - python >=3.7

test:
  imports:
    - napari_j
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/MontpellierRessourcesImagerie/napari-J
  summary: A plugin to exchange data with FIJI and to use FIJI image analysis from napari
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
